### ISSUE TITLE
Latest macOS MPS support fails after fresh git clone

### ISSUE THREAD

**Issue by ChristianWeyer** [huggingface/speech-to-speech#33] opened 2024-08-22 16:10 UTC
Hi @andimarafioti 

I just cloned the repo (0c53fda7dd5682155186a03386434a1c1cf50212) and did a `pip install`.

Then I ran
`python s2s_pipeline.py --local_mac_optimal_settings`

and got this error:

```
2024-08-22 17:42:22,716 - parler_tts.modeling_parler_tts - WARNING - Flash attention 2 is not installed
Using cache found in /Users/christianweyer/.cache/torch/hub/snakers4_silero-vad_master
weights.npz: 100%|█████████████████████████████████████████████████████████████████| 1.51G/1.51G [02:18<00:00, 10.9MB/s]
mlx_models/distil-large-v3/config.json: 100%|██████████████████████████████████████████| 268/268 [00:00<00:00, 1.42MB/s]
model.safetensors.index.json: 100%|████████████████████████████████████████████████| 16.5k/16.5k [00:00<00:00, 16.3MB/s]
generation_config.json: 100%|██████████████████████████████████████████████████████████| 181/181 [00:00<00:00, 1.23MB/s]
added_tokens.json: 100%|███████████████████████████████████████████████████████████████| 306/306 [00:00<00:00, 2.91MB/s]
sample_finetune.py: 100%|██████████████████████████████████████████████████████████| 6.40k/6.40k [00:00<00:00, 9.91MB/s]
modeling_phi3.py: 100%|█████████████████████████████████████████████████████████████| 73.2k/73.2k [00:00<00:00, 493kB/s]
config.json: 100%|█████████████████████████████████████████████████████████████████████| 967/967 [00:00<00:00, 11.5MB/s]
configuration_phi3.py: 100%|███████████████████████████████████████████████████████| 11.2k/11.2k [00:00<00:00, 33.8MB/s]
tokenizer_config.json: 100%|███████████████████████████████████████████████████████| 3.44k/3.44k [00:00<00:00, 15.5MB/s]
special_tokens_map.json: 100%|█████████████████████████████████████████████████████████| 599/599 [00:00<00:00, 2.01MB/s]
tokenizer.model: 100%|███████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 1.35MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████| 1.94M/1.94M [00:01<00:00, 999kB/s]
model-00002-of-00002.safetensors: 100%|████████████████████████████████████████████| 2.67G/2.67G [06:33<00:00, 6.79MB/s]
model-00001-of-00002.safetensors: 100%|████████████████████████████████████████████| 4.97G/4.97G [11:37<00:00, 7.12MB/s]
Fetching 13 files: 100%|████████████████████████████████████████████████████████████████| 13/13 [11:38<00:00, 53.72s/it]
2024-08-22 17:56:38,801 - __main__ - ERROR - Error importing MeloTTSHandler. You might need to run: python -m unidic download
Traceback (most recent call last):
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/MeCab/__init__.py", line 137, in __init__
    super(Tagger, self).__init__(args)
RuntimeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/christianweyer/Sources/speech-to-speech/s2s_pipeline.py", line 1143, in <module>
    main()
  File "/Users/christianweyer/Sources/speech-to-speech/s2s_pipeline.py", line 1122, in main
    raise e
  File "/Users/christianweyer/Sources/speech-to-speech/s2s_pipeline.py", line 1119, in main
    from TTS.melotts import MeloTTSHandler
  File "/Users/christianweyer/Sources/speech-to-speech/TTS/melotts.py", line 1, in <module>
    from melo.api import TTS
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/api.py", line 13, in <module>
    from . import utils
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/utils.py", line 13, in <module>
    from melo.text.cleaner import clean_text
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/text/cleaner.py", line 1, in <module>
    from . import chinese, japanese, english, chinese_mix, korean, french, spanish
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/text/japanese.py", line 367, in <module>
    _TAGGER = MeCab.Tagger()
              ^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/MeCab/__init__.py", line 139, in __init__
    raise RuntimeError(error_info(rawargs)) from ee
RuntimeError:
----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments:
default dictionary path: /Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/unidic/dicdir
[ifs] no such file or directory: /Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/unidic/dicdir/mecabrc
----------------------------------------------------------

```

I did a manual `python -m unidic download` after that error and reran `python s2s_pipeline.py --local_mac_optimal_settings`. OK.
Then after downloading all the models lot of warnings show up.

Eventually, I was able to speak to it.
But then...

```
USER: 1, 2, 3.
ASSISTANT: 1, 2, 3.
Exception in thread Thread-6 (run):
Traceback (most recent call last):
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/christianweyer/Sources/speech-to-speech/baseHandler.py", line 37, in run
    for output in self.process(input):
  File "/Users/christianweyer/Sources/speech-to-speech/TTS/melotts.py", line 48, in process
    audio_chunk = self.model.tts_to_file(llm_sentence, self.speaker_id, quiet=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/api.py", line 100, in tts_to_file
    bert, ja_bert, phones, tones, lang_ids = utils.get_text_for_tts_infer(t, language, self.hps, device, self.symbol_to_id)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/utils.py", line 23, in get_text_for_tts_infer
    norm_text, phone, tone, word2ph = clean_text(text, language_str)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/text/cleaner.py", line 12, in clean_text
    phones, tones, word2ph = language_module.g2p(norm_text)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/text/english.py", line 242, in g2p
    phone_list = list(filter(lambda p: p != " ", _g2p(w)))
                                                 ^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/g2p_en/g2p.py", line 162, in __call__
    tokens = pos_tag(words)  # tuples of (word, tag)
             ^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/nltk/tag/__init__.py", line 168, in pos_tag
    tagger = _get_tagger(lang)
             ^^^^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/nltk/tag/__init__.py", line 110, in _get_tagger
    tagger = PerceptronTagger()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/nltk/tag/perceptron.py", line 183, in __init__
    self.load_from_json(lang)
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/nltk/tag/perceptron.py", line 273, in load_from_json
    loc = find(f"taggers/averaged_perceptron_tagger_{lang}/")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource averaged_perceptron_tagger_eng not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger_eng')

  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger_eng/

  Searched in:
    - '/Users/christianweyer/nltk_data'
    - '/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/nltk_data'
    - '/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/share/nltk_data'
    - '/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

```

Any idea what is wrong here?

Thanks!

**Comment by andimarafioti** [comment] 2024-08-22 16:21
Hi! You are missing the nltk package, it can be fixed by running 

```python
import nltk
nltk.download('averaged_perceptron_tagger_eng')
```

**Comment by andimarafioti** [comment] 2024-08-22 16:22
There are a few lines in the code that aimed at this but clearly are not sufficient, nltk is a bit annoying like that. I'll try to handle this.

**Comment by andimarafioti** [comment] 2024-08-22 16:27
I just tried to reproduce this in my machine and I don't have the 'averaged_perceptron_tagger_eng' but it still runs, weird

**Comment by andimarafioti** [comment] 2024-08-22 16:31
I think I know what is happening. In any case, I'll just add the check to the code. Can you pull and recheck? it should work now.

**Comment by andimarafioti** [comment] 2024-08-22 16:36
@ChristianWeyer  in case you are not being pinged, I'll log off for the day soon :)

**Comment by ChristianWeyer** [comment] 2024-08-22 16:47
... I am here ... how can I help?

**Comment by ChristianWeyer** [comment] 2024-08-22 16:50
Works now.
The lag between the written response and the TTS is quite large, though.

**Comment by andimarafioti** [comment] 2024-08-22 17:19
What machine are you running this on?

**Comment by ChristianWeyer** [comment] 2024-08-22 17:34
MBP M3 Max 128GB.

**Comment by andimarafioti** [comment] 2024-08-22 17:45
That's surprising then. Is it larger than on this video? https://www.linkedin.com/posts/andresmarafioti_introducing-hugging-faces-speech-to-speech-activity-7231548059388723201-1wIe?utm_source=share&utm_medium=member_desktop

**Comment by ChristianWeyer** [comment] 2024-08-22 17:52
Yes, it is larger.

**Comment by ChristianWeyer** [comment] 2024-08-22 18:10
Here is a video:

https://github.com/user-attachments/assets/42be0e56-ab07-4645-a49d-9b3ff1017189



Feels laggy, don't you think?

BTW, here is the startup log:
```
❯ python s2s_pipeline.py --local_mac_optimal_settings
2024-08-22 20:00:57,732 - parler_tts.modeling_parler_tts - WARNING - Flash attention 2 is not installed
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/christianweyer/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
Using cache found in /Users/christianweyer/.cache/torch/hub/snakers4_silero-vad_master
Fetching 13 files: 100%|██████████████████████████████████████████████████| 13/13 [00:00<00:00, 19287.57it/s]
auto
/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/melo/download_utils.py:64: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(ckpt_path, map_location=device)
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/Users/christianweyer/miniconda3/envs/hf-speech-to-speech/lib/python3.11/site-packages/torch/nn/functional.py:4552: UserWarning: MPS: The constant padding of more than 3 dimensions is not currently supported natively. It uses View Ops default implementation to run. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Pad.mm:472.)
  return torch._C._nn.pad(input, pad, mode, value)
```

**Comment by scalar27** [comment] 2024-08-22 18:39
I don't real see much or any difference between the lag in those two videos.  They are both using MeloTTS. I have a M1 Max 64 Gb and get similar results if I run with the new flag: --local_mac_optimal_settings 
because that flag tells the code to  MeloTTS instead of Parler.  Parler is working if I set --play_steps_s 10 and it sounds great but there is a definite lag.  Would love to figure out how to reduce that.

**Comment by andimarafioti** [comment] 2024-08-23 06:40
I agree @ChristianWeyer , I think your video is similar to what I've experienced and my video. Maybe you were mentally comparing it with the version running on a cuda gpu, which is faster. 

I'm closing this issue since it seems to work after a fresh git clone ! 🚀

**Closed by andimarafioti** 2024-08-23 06:40 UTC

**Comment by andimarafioti** [comment] 2024-08-23 10:00
I found some ways to make it faster @ChristianWeyer ;)

**Comment by andimarafioti** [comment] 2024-08-23 12:14
https://github.com/huggingface/speech-to-speech/pull/41

**Comment by ChristianWeyer** [comment] 2024-08-24 13:51
Nice :-) @andimarafioti. Thanks so much.
